# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\AddGui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(600, 400)
        self.SpecTable = QtWidgets.QTableWidget(Dialog)
        self.SpecTable.setGeometry(QtCore.QRect(20, 30, 281, 341))
        self.SpecTable.setObjectName("SpecTable")
        self.SpecTable.setColumnCount(0)
        self.SpecTable.setRowCount(0)
        self.CompleteButton = QtWidgets.QPushButton(Dialog)
        self.CompleteButton.setGeometry(QtCore.QRect(380, 140, 150, 51))
        self.CompleteButton.setObjectName("CompleteButton")
        self.BackButton = QtWidgets.QPushButton(Dialog)
        self.BackButton.setGeometry(QtCore.QRect(380, 200, 150, 51))
        self.BackButton.setObjectName("BackButton")
        self.NotificationLabel = QtWidgets.QLabel(Dialog)
        self.NotificationLabel.setGeometry(QtCore.QRect(380, 100, 150, 30))
        self.NotificationLabel.setText("")
        self.NotificationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.NotificationLabel.setObjectName("NotificationLabel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.CompleteButton.setText(_translate("Dialog", "Добавить"))
        self.BackButton.setText(_translate("Dialog", "Назад"))
