# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\BrandInfo.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.InfoTable = QtWidgets.QTableWidget(self.centralwidget)
        self.InfoTable.setGeometry(QtCore.QRect(370, 70, 400, 400))
        self.InfoTable.setObjectName("InfoTable")
        self.BrandNameLabel = QtWidgets.QLabel(self.centralwidget)
        self.BrandNameLabel.setGeometry(QtCore.QRect(30, 70, 300, 30))
        self.BrandNameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.BrandNameLabel.setObjectName("BrandNameLabel")
        self.BrandLogoLabel = QtWidgets.QLabel(self.centralwidget)
        self.BrandLogoLabel.setGeometry(QtCore.QRect(30, 100, 300, 300))
        self.BrandLogoLabel.setText("")
        self.BrandLogoLabel.setPixmap(QtGui.QPixmap("C:/Users/T/Pictures/c063ae84ea55308794074b136333b0ed~c5_720x720.jpeg"))
        self.BrandLogoLabel.setScaledContents(True)
        self.BrandLogoLabel.setObjectName("BrandLogoLabel")
        self.BackButton = QtWidgets.QPushButton(self.centralwidget)
        self.BackButton.setGeometry(QtCore.QRect(40, 410, 135, 60))
        self.BackButton.setObjectName("BackButton")
        self.NextButton = QtWidgets.QPushButton(self.centralwidget)
        self.NextButton.setGeometry(QtCore.QRect(190, 410, 135, 60))
        self.NextButton.setObjectName("NextButton")
        self.EditButton = QtWidgets.QPushButton(self.centralwidget)
        self.EditButton.setGeometry(QtCore.QRect(370, 480, 150, 60))
        self.EditButton.setObjectName("EditButton")
        self.DeleteButton = QtWidgets.QPushButton(self.centralwidget)
        self.DeleteButton.setGeometry(QtCore.QRect(620, 480, 150, 60))
        self.DeleteButton.setObjectName("DeleteButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Бренды"))
        self.BrandNameLabel.setText(_translate("MainWindow", "Имя Бренда"))
        self.BackButton.setText(_translate("MainWindow", "Назад"))
        self.NextButton.setText(_translate("MainWindow", "Модели"))
        self.EditButton.setText(_translate("MainWindow", "Изменить"))
        self.DeleteButton.setText(_translate("MainWindow", "Удалить"))
