# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\EditGui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(600, 400)
        self.EditButton = QtWidgets.QPushButton(Dialog)
        self.EditButton.setGeometry(QtCore.QRect(360, 200, 150, 60))
        self.EditButton.setObjectName("EditButton")
        self.SpecLine = QtWidgets.QLineEdit(Dialog)
        self.SpecLine.setGeometry(QtCore.QRect(320, 130, 231, 31))
        self.SpecLine.setObjectName("SpecLine")
        self.SpecNameLabel = QtWidgets.QLabel(Dialog)
        self.SpecNameLabel.setGeometry(QtCore.QRect(320, 100, 231, 31))
        self.SpecNameLabel.setText("")
        self.SpecNameLabel.setObjectName("SpecNameLabel")
        self.BackButton = QtWidgets.QPushButton(Dialog)
        self.BackButton.setGeometry(QtCore.QRect(360, 270, 150, 60))
        self.BackButton.setObjectName("BackButton")
        self.SpecTable = QtWidgets.QTableWidget(Dialog)
        self.SpecTable.setGeometry(QtCore.QRect(20, 30, 271, 341))
        self.SpecTable.setObjectName("SpecTable")
        self.SpecTable.setColumnCount(0)
        self.SpecTable.setRowCount(0)
        self.NotificationLabel = QtWidgets.QLabel(Dialog)
        self.NotificationLabel.setGeometry(QtCore.QRect(320, 170, 231, 31))
        self.NotificationLabel.setText("")
        self.NotificationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.NotificationLabel.setObjectName("NotificationLabel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.EditButton.setText(_translate("Dialog", "Изменить"))
        self.BackButton.setText(_translate("Dialog", "Назад"))
