# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ListWidget = QtWidgets.QListWidget(self.centralwidget)
        self.ListWidget.setGeometry(QtCore.QRect(30, 30, 370, 540))
        self.ListWidget.setObjectName("ListWidget")
        self.InfoWidget = QtWidgets.QWidget(self.centralwidget)
        self.InfoWidget.setGeometry(QtCore.QRect(410, 30, 360, 541))
        self.InfoWidget.setObjectName("InfoWidget")
        self.InfoButton = QtWidgets.QPushButton(self.InfoWidget)
        self.InfoButton.setGeometry(QtCore.QRect(30, 380, 135, 60))
        self.InfoButton.setObjectName("InfoButton")
        self.NextButton = QtWidgets.QPushButton(self.InfoWidget)
        self.NextButton.setGeometry(QtCore.QRect(200, 380, 135, 60))
        self.NextButton.setObjectName("NextButton")
        self.NameLabel = QtWidgets.QLabel(self.InfoWidget)
        self.NameLabel.setGeometry(QtCore.QRect(30, 329, 301, 51))
        self.NameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.NameLabel.setObjectName("NameLabel")
        self.PicLabel = QtWidgets.QLabel(self.InfoWidget)
        self.PicLabel.setGeometry(QtCore.QRect(30, 30, 300, 300))
        self.PicLabel.setText("")
        self.PicLabel.setPixmap(QtGui.QPixmap("C:/Users/T/Pictures/FPNorKVUcCcp3Oh.jpg"))
        self.PicLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.PicLabel.setObjectName("PicLabel")
        self.PicLabel.setScaledContents(True)
        self.BackButton = QtWidgets.QPushButton(self.InfoWidget)
        self.BackButton.setGeometry(QtCore.QRect(0, 500, 135, 41))
        self.BackButton.setObjectName("BackButton")
        self.AddButton = QtWidgets.QPushButton(self.InfoWidget)
        self.AddButton.setGeometry(QtCore.QRect(130, 500, 135, 41))
        self.AddButton.setObjectName("AddButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.InfoButton.setText(_translate("MainWindow", "Информация"))
        self.NextButton.setText(_translate("MainWindow", "Модели"))
        self.NameLabel.setText(_translate("MainWindow", "Название Бренда"))
        self.BackButton.setText(_translate("MainWindow", "Назад"))
        self.AddButton.setText(_translate("MainWindow", "Добавить"))
